USE [master]
GO

/****** Object:  Database [Banquent_Booking]    Script Date: 6/27/2021 8:53:22 PM ******/
DROP DATABASE [Banquent_Booking]
GO

/****** Object:  Database [Banquent_Booking]    Script Date: 6/27/2021 8:53:22 PM ******/
CREATE DATABASE [Banquent_Booking]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Banquent_Booking', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\Banquent_Booking.mdf' , SIZE = 3264KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Banquent_Booking_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\Banquent_Booking_log.ldf' , SIZE = 816KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Banquent_Booking] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Banquent_Booking].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Banquent_Booking] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Banquent_Booking] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Banquent_Booking] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Banquent_Booking] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Banquent_Booking] SET ARITHABORT OFF 
GO

ALTER DATABASE [Banquent_Booking] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [Banquent_Booking] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Banquent_Booking] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Banquent_Booking] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Banquent_Booking] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Banquent_Booking] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Banquent_Booking] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Banquent_Booking] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Banquent_Booking] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Banquent_Booking] SET  ENABLE_BROKER 
GO

ALTER DATABASE [Banquent_Booking] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Banquent_Booking] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Banquent_Booking] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Banquent_Booking] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Banquent_Booking] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Banquent_Booking] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Banquent_Booking] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Banquent_Booking] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Banquent_Booking] SET  MULTI_USER 
GO

ALTER DATABASE [Banquent_Booking] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Banquent_Booking] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Banquent_Booking] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Banquent_Booking] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [Banquent_Booking] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Banquent_Booking] SET  READ_WRITE 
GO

