//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBAPP_portfolioMaker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AboutInfo
    {
        public string ID { get; set; }
        public string dob { get; set; }
        public string Heading { get; set; }
        public string Sub_Heading { get; set; }
        public string Short_Description { get; set; }
        public string Long_Description { get; set; }
        public string Website { get; set; }
    }
}
