//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBAPP_portfolioMaker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BasicInfo
    {
        public string ID { get; set; }
        public int Liscence_Key { get; set; }
        public string Job_title { get; set; }
        public string Job_Description { get; set; }
        public string Experties { get; set; }
        public string Avatar_Icon { get; set; }
        public string Theme { get; set; }
    }
}
