//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBAPP_portfolioMaker.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class C_WEB_Search
    {

        public string ID { get; set; }
        public string Name { get; set; }
        public string Profession { get; set; }
        [Column("Project_Name")]
        public string Project_Name { get; set; }
        public string Issue_Date { get; set; }
        public string Skills { get; set; }
        public string Organization_Name { get; set; }
    }
}
