//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBAPP_portfolioMaker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class contact
    {
        public string user_id { get; set; }
        public int Cid { get; set; }
        public string cname { get; set; }
        public string cemail { get; set; }
        public string csubject { get; set; }
        public string cmessage { get; set; }
    
        public virtual admin_users admin_users { get; set; }
    }
}
