//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBAPP_portfolioMaker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomizeTheme
    {
        public string Theme { get; set; }
        public string ID { get; set; }
        public string Font_Color { get; set; }
        public string Background_Color { get; set; }
        public string fontStyle { get; set; }
        public int fontSize { get; set; }
    }
}
