//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBAPP_portfolioMaker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Details_ofWebView
    {
        public string PIC { get; set; }
        public string WPIC { get; set; }
        public string Uid { get; set; }
        public string name { get; set; }
        public string UPro { get; set; }
        public string SN { get; set; }
        public string URL { get; set; }
        public string SDes { get; set; }
        public string MHead { get; set; }
        public string SHead { get; set; }
        public string dob { get; set; }
        public string Email { get; set; }
        public string Cell { get; set; }
        public string Ldes { get; set; }
        public string S_ID { get; set; }
        public string Skills { get; set; }
        public string Points { get; set; }
        public string Jtitle { get; set; }
        public string Oname { get; set; }
        public string Year_Work { get; set; }
        public string WorkDes { get; set; }
        public string Cageg { get; set; }
        public string Lpro { get; set; }
        public string PicOFPro { get; set; }
        public string des { get; set; }
        public string Pname { get; set; }
    }
}
