//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBAPP_portfolioMaker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExperienceWorkHireDetail
    {
        public string Name { get; set; }
        public string Profile_Pic { get; set; }
        public string Wallpaper { get; set; }
        public string Profession { get; set; }
        public string Categrory { get; set; }
        public string Contact_No { get; set; }
        public string Email { get; set; }
        public string Adress { get; set; }
        public string Organization_Name { get; set; }
        public string Working_Description { get; set; }
        public string Working_Since { get; set; }
    }
}
