//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBAPP_portfolioMaker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class History
    {
        public string UserID { get; set; }
        public string ActionPerform { get; set; }
        public string Log_ { get; set; }
        public string Before_log { get; set; }
        public string After_log { get; set; }
        public string Date_time { get; set; }
    }
}
