//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBAPP_portfolioMaker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Main_WEB_Search
    {
        public string Name { get; set; }
        public string Profession { get; set; }
        public string PName { get; set; }
        public string IDate { get; set; }
        public string Skills { get; set; }
        public string OName { get; set; }
    }
}
