//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBAPP_portfolioMaker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OwnerInfo
    {
        public string AdminID { get; set; }
        public string AdminPass { get; set; }
        public string Request_Recieved { get; set; }
        public string Contact_No { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
    }
}
