//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBAPP_portfolioMaker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Owner_Setup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Owner_Setup()
        {
            this.Owner_Setup1 = new HashSet<Owner_Setup>();
        }
    
        public string AdminID { get; set; }
        public string AdminPass { get; set; }
        public string NewRequest { get; set; }
        public string Number { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Owner_Setup> Owner_Setup1 { get; set; }
        public virtual Owner_Setup Owner_Setup2 { get; set; }
    }
}
