//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBAPP_portfolioMaker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class personal_setup
    {
        public string user_id { get; set; }
        public string profilepic { get; set; }
        public string name { get; set; }
        public string homewallpaper { get; set; }
        public string professions { get; set; }
        public string location { get; set; }
        public string mobile { get; set; }
        public string emailuser { get; set; }
    
        public virtual admin_users admin_users { get; set; }
    }
}
