//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBAPP_portfolioMaker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectInfo
    {
        public string ID { get; set; }
        public string Project_Name { get; set; }
        public string Pics_of_project { get; set; }
        public string Link_of_project { get; set; }
        public string Description { get; set; }
    }
}
