//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBAPP_portfolioMaker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Theme_Customize
    {
        public string Theme { get; set; }
        public string user_id { get; set; }
        public string fcolor { get; set; }
        public string bcolor { get; set; }
        public string fontStyle { get; set; }
        public int fontSize { get; set; }
    
        public virtual admin_users admin_users { get; set; }
        public virtual Theme Theme1 { get; set; }
    }
}
