//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBAPP_portfolioMaker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkingExperience
    {
        public string ID { get; set; }
        public string Categrory { get; set; }
        public string Job_Title { get; set; }
        public string Working_Since { get; set; }
        public string Organization_Name { get; set; }
        public string Working_Description { get; set; }
    }
}
