//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EMPLOYEE()
        {
            this.EMPLOYEE1 = new HashSet<EMPLOYEE>();
            this.PROJECT_PARTICIPATION = new HashSet<PROJECT_PARTICIPATION>();
        }
    
        public int empno { get; set; }
        public string name { get; set; }
        public string job { get; set; }
        public Nullable<int> boss { get; set; }
        public string hiredate { get; set; }
        public Nullable<decimal> salary { get; set; }
        public Nullable<decimal> comm { get; set; }
        public Nullable<int> deptno { get; set; }
    
        public virtual DEPARTMENT DEPARTMENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMPLOYEE> EMPLOYEE1 { get; set; }
        public virtual EMPLOYEE EMPLOYEE2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROJECT_PARTICIPATION> PROJECT_PARTICIPATION { get; set; }
    }
}
