//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpTable
    {
        public int empno { get; set; }
        public string name { get; set; }
        public string job { get; set; }
        public Nullable<int> boss { get; set; }
        public string hiredate { get; set; }
        public Nullable<decimal> salary { get; set; }
        public Nullable<decimal> comm { get; set; }
        public Nullable<int> deptno { get; set; }
    }
}
